package com.derivedmed.proj.dao;

import com.derivedmed.proj.model.Conf;
import com.derivedmed.proj.util.QueryGenerator;
import com.derivedmed.proj.util.rsparser.ResultSetParser;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class ConfDao implements CrudDao<Conf> {

    private static Logger LOGGER = LogManager.getLogger(ConfDao.class);
    private final String SQL_EXCEPTION = "SQL exception Conf DAO";

    @Override
    public int create(Conf conf) {
        int autoGeneratedId = 0;
        QueryGenerator queryGenerator = new QueryGenerator();
        String sql = queryGenerator.insert("confs", new String[]{"conf_name", "conf_place", "conf_date"})
                .generate();
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = queryGenerator.setValues(connectionProxy
                     .prepareStatement(sql, Statement.RETURN_GENERATED_KEYS), new Object[]{conf.getName(), conf.getPlace(), conf.getDate()})) {
            preparedStatement.executeUpdate();
            ResultSet id = preparedStatement.getGeneratedKeys();
            id.next();
            autoGeneratedId = id.getInt(1);
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return autoGeneratedId;
    }

    @Override
    public Conf getByID(int id) {
        List<Conf> conf = new ArrayList<>();
        QueryGenerator queryGenerator = new QueryGenerator();
        String sql = queryGenerator.select("*")
                .from("confs")
                .where("conf_id", "=")
                .generate();
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = queryGenerator.setValues(connectionProxy
                     .prepareStatement(sql), new Object[]{id})) {
            conf = ResultSetParser.getInstance().parse(preparedStatement.executeQuery(), new Conf());
            if (!conf.isEmpty()) {
                return conf.get(0);
            }
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return new Conf();
    }

    @Override
    public boolean update(Conf conf) {
        QueryGenerator queryGenerator = new QueryGenerator();
        String sql = queryGenerator.update("confs")
                .set(new String[]{"conf_name", "conf_place", "conf_date"})
                .where("conf_id", "=")
                .generate();
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = queryGenerator.setValues(connectionProxy
                     .prepareStatement(sql), new Object[]{conf.getName(), conf.getPlace(), conf.getDate(), conf.getId()})) {
            preparedStatement.executeUpdate();
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            return false;
        }
        return true;
    }

    @Override
    public boolean delete(int id) {
        QueryGenerator queryGenerator = new QueryGenerator();
        String sql = queryGenerator.delete("confs")
                .where("conf_id", "=")
                .generate();
        String DELETE_SQL = "delete from confs where conf_id =?";
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = queryGenerator.setValues(connectionProxy.prepareStatement(sql), new Object[]{id})) {
            preparedStatement.executeUpdate();
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            return false;
        }
        return true;
    }

    @Override
    public List<Conf> getAll() {
        QueryGenerator queryGenerator = new QueryGenerator();
        String sql = queryGenerator.select("*")
                .from("confs")
                .generate();
        ArrayList<Conf> resultList = new ArrayList<>();
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement(sql)) {
            resultList = ResultSetParser.getInstance().parse(preparedStatement.executeQuery(), new Conf());
            if (!resultList.isEmpty()) {
                return resultList;
            }
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return resultList;
    }

    @Override
    public boolean clearAll() {
        QueryGenerator queryGenerator = new QueryGenerator();
        String sql = queryGenerator.delete("confs").generate();
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             Statement statement = connectionProxy.createStatement()) {
            statement.executeUpdate(sql);
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            return false;
        }
        return true;
    }
}
