package com.derivedmed.proj.dao;

import com.derivedmed.proj.model.*;
import com.derivedmed.proj.util.PreparedStatmentCompilier;
import com.derivedmed.proj.util.rsparser.ResultSetParser;
import org.apache.commons.lang3.time.DateUtils;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class ReportDao implements CrudDao<Report> {

    private static final Logger LOGGER = LogManager.getLogger(ReportDao.class);
    private static final String SQL_EXCEPTION = "SQL exception Report DAO";
    private static final String CREATE_SQL = "insert into reports (conf_id, report_name, report_desk) values (?, ?, ?)";
    private static final String GET_BY_ID_SQL = "select * from reports where report_id = ?";
    private static final String UPDATE_SQL = "update reports set conf_id = ?, report_name = ?, report_desk = ? " +
            "where report_id = ?";
    private static final String DELETE_SQL = "delete from reports where report_id = ?";
    private static final String GET_ALL_SQL = "select * from reports";
    private static final String CLEAR_ALL_SQL = "delete from reports";
    private static final String GET_REPORTS_BY_USER_ID_SQL = "select r.report_id, r.conf_id, report_name, report_desk " +
            "from reports r join users_reports ur on r.report_id = ur.report_id where ur.user_id = ?";
    private static final String CONFIRM_OFFER_SECOND_SQL = "update users_reports set active_speaker = ?, confirmed = ?" +
            ", by_speaker = ?, by_moder = ? where report_id = ? and user_id <> ?";
    private static final String OFFERED_BY_SPEAKER_SQL = "select reports.report_id,conf_id,report_name,report_desk" +
            " from reports join users_reports on reports.report_id = users_reports.report_id where user_id =?" +
            " and by_speaker =? and by_moder =?";
    private static final String VOTED_BY_USER_SQL = "select report_id from users_reports where user_id =? and rating > 0";
    private static final String REPORTS_OFFERED_BY_SPEAKERS_SQL = "select c.conf_id, confirmed, ur.user_id, " +
            "ur.report_id, u.login, r.report_name, c.conf_name, c.confDate from users u " +
            "join users_reports ur on u.user_id = ur.user_id " +
            "join reports r on ur.report_id = r.report_id " +
            "join confs c on r.conf_id = c.conf_id " +
            "where u.role_id = ? and by_speaker = ? and confirmed = ? and active_speaker = ? ";
    private static final String DATA_FOR_NOTIFICATIONS_SQL = "select r.report_name, u.email, u.login, c.conf_name," +
            " c.conf_place, c.confDate from users u " +
            "join users_reports ur on u.user_id = ur.user_id " +
            "join reports r on ur.report_id = r.report_id " +
            "join confs c on r.conf_id = c.conf_id where c.confDate > ? and c.confDate < ? group by u.email";
    private static final String IS_SPEAKER_EXIST_SQL = "select* from users_reports where user_id =? and report_id=?";
    private static final String UPDATE_OR_INSERT_SQL = "select * from users_reports where user_id = ? and report_id = ?";
    private static final String DELETE_FROM_USERS_REPORTS_SQL = " delete from users_reports where user_id = ? " +
            "and report_id = ?";
    private static final String DELETE_REPORT_FROM_USERS_REPORTS_SQ = "delete from users_reports where report_id = ?";
    private static final String GET_REPORTS_WITH_CONF_SQL = " select conf_name, confDate, report_id from reports r " +
            "join confs c on r.conf_id = c.conf_id ";
    private static final String GET_REPORTS_WITH_SPEAKERS_SQL = " select login, report_id from users u " +
            "join users_reports ur on u.user_id = ur.user_id " +
            "where active_speaker = ?";
    private static final String CONFIRM_OFFER_UPDATE = "update users_reports set active_speaker = ?, confirmed = ? " +
            "where user_id = ? and report_id = ?";
    private static final String CONFIRM_OFFER_INSERT = "insert into users_reports (active_speaker, confirmed, " +
            "user_id, report_id) values(?, ?, ?, ?)";
    private static final String UPDATE_OR_INSERT_INSERT_SQL = "insert into users_reports (active_speaker, by_speaker," +
            " by_moder, confirmed, user_id, report_id) values(?,?,?,?,?,?)";
    private static final String UPDATE_OR_INSERT_UPDATE_SQL = "update users_reports set active_speaker = ?, " +
            "by_speaker = ?, by_moder = ?, confirmed = ? where user_id = ? and report_id = ?";
    private final ResultSetParser RESULT_SET_PARSER = ResultSetParser.getInstance();
    private final TransactionManager TRANSACTION_MANAGER = TransactionManager.getInstance();


    @Override
    public int create(Report report) {
        int autoGeneratedId;
        try (ConnectionProxy connectionProxy = TRANSACTION_MANAGER.getConnection();
             PreparedStatement preparedStatement = PreparedStatmentCompilier.setValues(connectionProxy
                     .prepareStatement(CREATE_SQL, Statement.RETURN_GENERATED_KEYS),
                     report.getConf_id(), report.getReportName(), report.getReportDescription())) {
            preparedStatement.executeUpdate();
            ResultSet id = preparedStatement.getGeneratedKeys();
            id.next();
            autoGeneratedId = id.getInt(1);
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            return 0;
        }
        return autoGeneratedId;
    }

    @Override
    public Report getByID(int id) {
        Report result = new Report();
        try (ConnectionProxy connectionProxy = TRANSACTION_MANAGER.getConnection();
             PreparedStatement preparedStatement = PreparedStatmentCompilier.setValues(connectionProxy
                     .prepareStatement(GET_BY_ID_SQL), id)) {
            List<Report> report = RESULT_SET_PARSER.parse(preparedStatement.executeQuery(), new Report());
            if (!report.isEmpty()) {
                result = report.get(0);
            }
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return result;
    }

    @Override
    public boolean update(Report report) {
        boolean result = true;
        try (ConnectionProxy connection = TRANSACTION_MANAGER.getConnection();
             PreparedStatement preparedStatement = PreparedStatmentCompilier.setValues(connection
                             .prepareStatement(UPDATE_SQL),
                     report.getConf_id(), report.getReportName(), report.getReportName(), report.getId())) {
            preparedStatement.executeUpdate();
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            result = false;
        }
        return result;
    }

    @Override
    public boolean delete(int id) {
        boolean result = true;
        try (ConnectionProxy connectionProxy = TRANSACTION_MANAGER.getConnection();
             PreparedStatement preparedStatement = PreparedStatmentCompilier.setValues(connectionProxy
                     .prepareStatement(DELETE_SQL), id)) {
            preparedStatement.executeUpdate();
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            result = false;
        }
        return result;
    }

    @Override
    public List<Report> getAll() {
        List<Report> resultList = new ArrayList<>();
        try (ConnectionProxy connectionProxy = TRANSACTION_MANAGER.getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement(GET_ALL_SQL)) {
            resultList = RESULT_SET_PARSER.parse(preparedStatement.executeQuery(), new Report());
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return resultList;
    }

    @Override
    public boolean clearAll() {
        boolean result = true;
        try (ConnectionProxy connectionProxy = TRANSACTION_MANAGER.getConnection();
             Statement statement = connectionProxy.createStatement()) {
            statement.executeUpdate(CLEAR_ALL_SQL);
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            result = false;
        }
        return result;
    }
    public List<ReportWithConf> getReportsWithConf(){
        List<ReportWithConf> reports = new ArrayList<>();
        try (ConnectionProxy connectionProxy = TRANSACTION_MANAGER.getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement(GET_REPORTS_WITH_CONF_SQL)) {
            ResultSet resultSet = preparedStatement.executeQuery();
            reports = RESULT_SET_PARSER.parse(resultSet, new ReportWithConf());

        } catch (SQLException e) {
            LOGGER.error(e);
        }
        return reports;
    }
    public boolean deleteFromUsersReports(int userId, int reportId){
        boolean result = false;
        try(ConnectionProxy connectionProxy = TRANSACTION_MANAGER.getConnection();
            PreparedStatement preparedStatement = PreparedStatmentCompilier.setValues(connectionProxy
                .prepareStatement(DELETE_FROM_USERS_REPORTS_SQL), userId,reportId)) {
            preparedStatement.executeUpdate();
            result = true;
        } catch (SQLException e) {
            LOGGER.error(e);
        }
        return result;
    }
    public boolean deleteFromUsersReports(int reportId){
        boolean result = false;
        try(ConnectionProxy connectionProxy = TRANSACTION_MANAGER.getConnection();
            PreparedStatement preparedStatement = PreparedStatmentCompilier.setValues(connectionProxy
                    .prepareStatement(DELETE_REPORT_FROM_USERS_REPORTS_SQ), reportId)) {
            preparedStatement.executeUpdate();
            result = true;
        } catch (SQLException e) {
            LOGGER.error(e);
        }
        return result;
    }

    public List<ReportWithSpeaker> getReportsWithSpeakers() {
        List<ReportWithSpeaker> reports = new ArrayList<>();
        try (ConnectionProxy connectionProxy = TRANSACTION_MANAGER.getConnection();
             PreparedStatement preparedStatement = PreparedStatmentCompilier.setValues(connectionProxy
                     .prepareStatement(GET_REPORTS_WITH_SPEAKERS_SQL), true)) {
            ResultSet resultSet = preparedStatement.executeQuery();
            reports = RESULT_SET_PARSER.parse(resultSet, new ReportWithSpeaker());
        } catch (SQLException e) {
            LOGGER.error(e);
        }
        return reports;
    }

    public List<Report> getReportsByUserId(int id) {
        List<Report> reports = new ArrayList<>();
        try (ConnectionProxy connectionProxy = TRANSACTION_MANAGER.getConnection();
             PreparedStatement preparedStatement = PreparedStatmentCompilier.setValues(connectionProxy
                     .prepareStatement(GET_REPORTS_BY_USER_ID_SQL), id)) {
            reports = RESULT_SET_PARSER.parse(preparedStatement.executeQuery(), new Report());
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return reports;
    }

    public boolean offerReport(int speakerId, int reportId, boolean bySpeaker) {
        boolean result = true;
        try (ConnectionProxy connectionProxy = TRANSACTION_MANAGER.getConnection()) {
            String offerReportSql = updateOrInsert(connectionProxy, speakerId, reportId);
            PreparedStatement preparedStatement = PreparedStatmentCompilier.setValues(connectionProxy
                            .prepareStatement(offerReportSql),false, bySpeaker, !bySpeaker, false, speakerId, reportId);
            preparedStatement.executeUpdate();
            preparedStatement.close();
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            result = false;
        }
        return result;
    }

    public boolean confirmOffer(int userId, int reportId) {
        boolean result = true;
        String sql;
        if (isSpeakerReportExist(userId, reportId)) {
            sql = CONFIRM_OFFER_UPDATE;
        } else {
            sql = CONFIRM_OFFER_INSERT;
        }
        try (ConnectionProxy connectionProxy = TRANSACTION_MANAGER.getConnection();
             PreparedStatement preparedStatement = PreparedStatmentCompilier.setValues(connectionProxy.prepareStatement(sql),
                     true, true, userId, reportId);
             PreparedStatement preparedStatement1 = PreparedStatmentCompilier.setValues(connectionProxy
                             .prepareStatement(CONFIRM_OFFER_SECOND_SQL),
                     false, false, false, false, reportId, userId)) {
            preparedStatement.executeUpdate();
            preparedStatement1.executeUpdate();
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            result = false;
        }
        return result;
    }

    public List<Report> getReportsOfferedBySpeakerOrModer(int userid, boolean bySpeaker) {
        List<Report> reports = new ArrayList<>();
        try (ConnectionProxy connectionProxy = TRANSACTION_MANAGER.getConnection();
             PreparedStatement preparedStatement = PreparedStatmentCompilier.setValues(connectionProxy
                             .prepareStatement(OFFERED_BY_SPEAKER_SQL),
                     userid, bySpeaker, !bySpeaker)) {
            reports = RESULT_SET_PARSER.parse(preparedStatement.executeQuery(), new Report());
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return reports;
    }


    public List<Integer> votedByUser(int user_id) {
        List<Integer> reports = new ArrayList<>();
        try (ConnectionProxy connectionProxy = TRANSACTION_MANAGER.getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement(VOTED_BY_USER_SQL)) {
            preparedStatement.setInt(1, user_id);
            ResultSet resultSet = preparedStatement.executeQuery();
            while (resultSet.next()) {
                reports.add(resultSet.getInt(1));
            }
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return reports;
    }

    public List<ReportOfferedBySpeaker> reportsOfferedBySpeakers(boolean confirmed) {

        List<ReportOfferedBySpeaker> reportOfferedBySpeakers = new ArrayList<>();
        try (ConnectionProxy connectionProxy = TRANSACTION_MANAGER.getConnection();
             PreparedStatement preparedStatement = PreparedStatmentCompilier.setValues(connectionProxy
                     .prepareStatement(REPORTS_OFFERED_BY_SPEAKERS_SQL), 3, true, confirmed, confirmed)) {
            reportOfferedBySpeakers = RESULT_SET_PARSER.parse(preparedStatement.executeQuery(), new ReportOfferedBySpeaker());
            if (!reportOfferedBySpeakers.isEmpty()) {
                return reportOfferedBySpeakers;
            }
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return reportOfferedBySpeakers;
    }

    public List<MailData> getDataForNotifications(Timestamp time) {
        List<MailData> result = new ArrayList<>();
        long oneDayMillis = DateUtils.MILLIS_PER_DAY;
        Timestamp nextDay = new Timestamp(time.getTime() + oneDayMillis);
        try (ConnectionProxy connectionProxy = TRANSACTION_MANAGER.getConnection();
             PreparedStatement preparedStatement = PreparedStatmentCompilier.setValues(connectionProxy
                     .prepareStatement(DATA_FOR_NOTIFICATIONS_SQL), time, nextDay)) {
            result = RESULT_SET_PARSER.parse(preparedStatement.executeQuery(), new MailData());
            if (!result.isEmpty()) {
                return result;
            }

        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return result;
    }

    private boolean isSpeakerReportExist(int userid, int reportid) {
        boolean exist = false;
        try (ConnectionProxy connectionProxy = TRANSACTION_MANAGER.getConnection();
             PreparedStatement preparedStatement = PreparedStatmentCompilier.setValues(connectionProxy
                     .prepareStatement(IS_SPEAKER_EXIST_SQL), userid, reportid)) {
            ResultSet resultSet = preparedStatement.executeQuery();
            exist = resultSet.next();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return exist;
    }

    private String updateOrInsert(ConnectionProxy connectionProxy, int speakerId, int reportId) {
        try (PreparedStatement preparedStatement = PreparedStatmentCompilier.setValues(connectionProxy
                .prepareStatement(UPDATE_OR_INSERT_SQL), speakerId, reportId);
             ResultSet resultSet = preparedStatement.executeQuery()) {
            if (!resultSet.next()) {
                return UPDATE_OR_INSERT_INSERT_SQL;
            }
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return UPDATE_OR_INSERT_UPDATE_SQL;
    }
}
