package com.derivedmed.proj.dao;

import com.derivedmed.proj.model.Role;
import com.derivedmed.proj.model.User;
import com.derivedmed.proj.util.PreparedStatmentCompilier;
import com.derivedmed.proj.util.QueryGenerator;
import com.derivedmed.proj.util.rsparser.ResultSetParser;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

public class UserDao implements CrudDao<User> {

    private static Logger LOGGER = LogManager.getLogger(UserDao.class);
    private static final String SQL_EXCEPTION = "SQL exception user DAO";
    private static final String createSql = "INSERT INTO users (role_id, login, password, email) VALUES (?, ?, ?, ?)";
    private static final String getByIdSql = "select * from users where user_id = ?";
    private static final String updateSql = "update users set login = ?, password = ?, role_id = ? where user_id = ?";
    private static final String deleteSql = "delete from users where user_id =?";
    private static final String getSpeakerByReportId = "select user_id from users_reports where report_id = ? and active_speaker = true";
    private static final String checkSpeakerActiveByDateSql = "SELECT users.* " +
            "FROM users " +
            "JOIN users_reports u ON users.user_id = u.user_id " +
            "JOIN reports r ON u.report_id = r.report_id " +
            "JOIN confs c ON r.conf_id = c.conf_id " +
            "WHERE role_id = ? AND active_speaker = ? AND c.confDate = ?";
    private static final String registerUserToReportSql = "insert into users_reports (user_id, report_id) values(?, ?)";
    private static final String getByRatingSql = "select * from users where role_id = ? order by rating desc";
    private static final String authSql = "select * from users where email = ? and password = ?";
    private static final String getByLoginSql = "select * from users where email = ?";
    private static final String getRoleIdSql = "select role_id from roles where role_name = ?";
    private static final String getRoleSql = "select role_name from roles where role_id = ?";

    @Override
    public int create(User user) {
        int autoGeneratedId;
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = PreparedStatmentCompilier.setValues(connectionProxy
                             .prepareStatement(createSql, Statement.RETURN_GENERATED_KEYS),
                     new Object[]{getRoleId(user.getRole()), user.getLogin(), user.getPassword(), user.getEmail()})) {
            preparedStatement.executeUpdate();
            ResultSet id = preparedStatement.getGeneratedKeys();
            id.next();
            autoGeneratedId = id.getInt(1);
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            return 0;
        }
        return autoGeneratedId;
    }

    @Override
    public User getByID(int id) {
        User user = new User();
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = PreparedStatmentCompilier.setValues(connectionProxy
                     .prepareStatement(getByIdSql), new Object[]{id})) {
            ArrayList<User> resultList = ResultSetParser.getInstance().parse(preparedStatement.executeQuery(), user);
            if (!resultList.isEmpty()) {
                user = resultList.get(0);
                user.setRole(getRole(user.getId()));
            }
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return user;
    }

    @Override
    public boolean update(User user) {
        QueryGenerator queryGenerator = new QueryGenerator();
        Object[] values = new Object[]{user.getLogin(), user.getPassword(), user.getRole_id(), user.getId()};
        try (ConnectionProxy connection = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = queryGenerator
                     .setValues(connection.prepareStatement(updateSql), values)) {
            preparedStatement.executeUpdate();
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            return false;
        }
        return true;
    }

    @Override
    public boolean delete(int id) {
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement(deleteSql)) {
            preparedStatement.setInt(1, id);
            preparedStatement.executeUpdate();
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            return false;
        }
        return true;
    }

    @Override
    public List<User> getAll() {
        List<User> resultList = new ArrayList<>();
        String GET_ALL_SQL = "select * from users";
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement(GET_ALL_SQL)) {
            resultList = ResultSetParser.getInstance().parse(preparedStatement.executeQuery(), new User());
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return resultList;
    }

    @Override
    public boolean clearAll() {
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             Statement statement = connectionProxy.createStatement()) {
            String DELETE_ALL_SQL = "DELETE FROM users";
            statement.executeUpdate(DELETE_ALL_SQL);
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            return false;
        }
        return true;
    }

    public boolean vote(int userId, int reportId, int rating) {
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement("update users_reports set rating =? where user_id =? and report_id = ?");
             PreparedStatement preparedStatement1 = connectionProxy.prepareStatement("update users set rating = rating + ? where user_id = ?")) {
            preparedStatement.setInt(1, rating);
            preparedStatement.setInt(2, userId);
            preparedStatement.setInt(3, reportId);
            preparedStatement.executeUpdate();
            preparedStatement1.setInt(1, rating);
            preparedStatement1.setInt(2, getSpeakerByReportId(connectionProxy, reportId));
            preparedStatement1.executeUpdate();
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            return false;
        }
        return true;
    }

    private int getSpeakerByReportId(ConnectionProxy connectionProxy, int reportId) {
        try (PreparedStatement preparedStatement = connectionProxy.prepareStatement(getSpeakerByReportId)) {
            preparedStatement.setInt(1, reportId);
            ResultSet resultSet = preparedStatement.executeQuery();
            if (resultSet.next()) {
                return resultSet.getInt(1);
            }
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return 0;
    }

    public List<User> getSpeakersFreeThisDate(Timestamp timestamp) {
        List<User> busyspeakers = busySpeakersByDate(timestamp);
        List<User> speakers = getSpeakersByRating();
        return speakers.stream().filter(s -> !busyspeakers.contains(s))
                .collect(Collectors.toList());
    }

    public List<User> busySpeakersByDate(Timestamp timestamp) {
        List<User> busySpeakers = new ArrayList<>();
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = PreparedStatmentCompilier.setValues(connectionProxy.prepareStatement(checkSpeakerActiveByDateSql),
                     new Object[]{getRoleId(Role.SPEAKER), true, timestamp})) {
            busySpeakers = ResultSetParser.getInstance().parse(preparedStatement.executeQuery(), new User());
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return busySpeakers;
    }

    public boolean registerUserToReport(int userId, int reportId) {
        try {
            try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
                 PreparedStatement preparedStatement = connectionProxy.prepareStatement(registerUserToReportSql)) {
                preparedStatement.setInt(1, userId);
                preparedStatement.setInt(2, reportId);
                preparedStatement.executeUpdate();
            }
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            return false;
        }
        return true;
    }

    public List<User> getSpeakersByRating() {
        ArrayList<User> resultList = new ArrayList<>();
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement(getByRatingSql)) {
            preparedStatement.setInt(1, getRoleId(Role.SPEAKER));
            resultList = ResultSetParser.getInstance().parse(preparedStatement.executeQuery(), new User());
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return resultList;
    }


    public boolean authUser(String login, String password) {
        boolean result = false;
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy
                     .prepareStatement(authSql)) {
            preparedStatement.setString(1, login);
            preparedStatement.setString(2, password);
            result = preparedStatement.executeQuery().next();
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return result;
    }

    public User getByLogin(String login) {
        User user = new User();
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy
                     .prepareStatement(getByLoginSql)) {
            preparedStatement.setString(1, login);
            ArrayList<User> users = ResultSetParser.getInstance().parse(preparedStatement.executeQuery(), new User());
            if (!users.isEmpty()) {
                user = users.get(0);
                user.setRole(getRole(user.getRole_id()));
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
        return user;
    }

    private int getRoleId(Role role) {
        int roleId = 0;
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement(getRoleIdSql)) {
            preparedStatement.setString(1, role.name());
            ResultSet resultSet = preparedStatement.executeQuery();
            if (resultSet.next()) {
                roleId = resultSet.getInt(1);
            }
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return roleId;
    }

    private Role getRole(int id) {
        Role role = null;
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement(getRoleSql)) {
            preparedStatement.setInt(1, id);
            ResultSet resultSet = preparedStatement.executeQuery();
            if (resultSet.next()) {
                role = Role.valueOf(resultSet.getString(1).toUpperCase());
            }
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return role;
    }
}
