package com.derivedmed.proj.dao;

import com.derivedmed.proj.model.Role;
import com.derivedmed.proj.model.User;
import com.derivedmed.proj.util.rsparser.ResultSetParser;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

public class UserDao implements CrudDao<User> {

    private static Logger LOGGER = LogManager.getLogger(UserDao.class);
    private final String SQL_EXCEPTION = "SQL exception user DAO";

    @Override
    public int create(User user) {
        int autoGeneratedId = 0;
        String CREATE_SQL = "INSERT INTO users (role_id, login, password) VALUES (?, ?, ?)";
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy
                     .prepareStatement(CREATE_SQL, Statement.RETURN_GENERATED_KEYS)) {
            preparedStatement.setInt(1, getRoleId(user.getRole()));
            preparedStatement.setString(2, user.getLogin());
            preparedStatement.setString(3, user.getPassword());
            preparedStatement.executeUpdate();
            ResultSet id = preparedStatement.getGeneratedKeys();
            id.next();
            autoGeneratedId = id.getInt(1);
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            return 0;
        }
        return autoGeneratedId;
    }

    @Override
    public User getByID(int id) {
        User user = new User();
        String GET_BY_ID_SQL = "SELECT * from users where user_id = ?";
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy
                     .prepareStatement(GET_BY_ID_SQL)) {
            preparedStatement.setInt(1, id);
            ArrayList<User> resultList = ResultSetParser.getInstance().parse(preparedStatement.executeQuery(), user);
            if (!resultList.isEmpty()) {
                user = resultList.get(0);
                user.setRole(getRole(user.getId()));
            } else {

            }
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return user;
    }

    @Override
    public boolean update(User user) {
        String UPDATE_SQL = "UPDATE users SET login = ?, password = ?, role_id = ? WHERE user_id = ?";
        try (ConnectionProxy connection = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(UPDATE_SQL)) {
            preparedStatement.setString(1, user.getLogin());
            preparedStatement.setString(2, user.getPassword());
            preparedStatement.setInt(3, user.getRole_id());
            preparedStatement.setInt(4, user.getId());
            preparedStatement.executeUpdate();
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            return false;
        }
        return true;
    }

    @Override
    public boolean delete(int id) {
        String DELETE_SQL = "delete from users where user_id =?";
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement(DELETE_SQL)) {
            preparedStatement.setInt(1, id);
            preparedStatement.executeUpdate();
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            return false;
        }
        return true;
    }

    @Override
    public List<User> getAll() {
        ArrayList<User> resultList = new ArrayList<>();
        String GET_ALL_SQL = "select * from users";
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement(GET_ALL_SQL)) {
            resultList = ResultSetParser.getInstance().parse(preparedStatement.executeQuery(), new User());
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return resultList;
    }

    @Override
    public boolean clearAll() {
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             Statement statement = connectionProxy.createStatement()) {
            String DELETE_ALL_SQL = "DELETE FROM users";
            statement.executeUpdate(DELETE_ALL_SQL);
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            return false;
        }
        return true;
    }

    public boolean vote(int userId, int reportId, int rating) {
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement("update users_reports set rating =? where user_id =? and report_id = ?");
             PreparedStatement preparedStatement1 = connectionProxy.prepareStatement("update users set rating = rating + ? where user_id = ?")) {
            preparedStatement.setInt(1, rating);
            preparedStatement.setInt(2, userId);
            preparedStatement.setInt(3, reportId);
            preparedStatement.executeUpdate();
            preparedStatement1.setInt(1, rating);
            preparedStatement1.setInt(2, getSpeakerByReportId(connectionProxy, reportId));
            preparedStatement1.executeUpdate();
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            return false;
        }
        return true;
    }

    private int getSpeakerByReportId(ConnectionProxy connectionProxy, int reportId) {
        try (PreparedStatement preparedStatement = connectionProxy.prepareStatement("select user_id from users_reports where report_id = ? and active_speaker = true")) {
            preparedStatement.setInt(1, reportId);
            ResultSet resultSet = preparedStatement.executeQuery();
            if (resultSet.next()) {
                return resultSet.getInt(1);
            }
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return 0;
    }

    public boolean isSpeakerFreeThisDate(User user, Timestamp timestamp) {
        boolean result = false;
        String CHECK_SPEAKER_ACTIV_BY_DATE_SQL = "select * from users_reports ur join reports r ON ur.report_id = r.report_id JOIN confs c ON r.conf_id = c.conf_id where ur.user_id =? and c.conf_date =? and ur.active_speaker =?;";
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement(CHECK_SPEAKER_ACTIV_BY_DATE_SQL)) {
            preparedStatement.setInt(1, user.getId());
            preparedStatement.setTimestamp(2, timestamp);
            preparedStatement.setBoolean(3, true);
            result = preparedStatement.executeQuery().next();
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            return false;
        }
        return !result;
    }

    public boolean registerUserToReport(int userId, int reportId) {
        try {
            String REGISTER_USER_TO_REPORT_SQL = "insert into users_reports (user_id, report_id) values(?, ?)";
            try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
                 PreparedStatement preparedStatement = connectionProxy.prepareStatement(REGISTER_USER_TO_REPORT_SQL)) {
                preparedStatement.setInt(1, userId);
                preparedStatement.setInt(2, reportId);
                preparedStatement.executeUpdate();
            }
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
            return false;
        }
        return true;
    }

    public List<User> getSpeakersByRating() {
        ArrayList<User> resultList = new ArrayList<>();
        String GET_SPEAKER_BY_RATING_SQL = "select * from users where role_id = ? order by rating desc";
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement(GET_SPEAKER_BY_RATING_SQL)) {
            preparedStatement.setInt(1, getRoleId(Role.SPEAKER));
            resultList = ResultSetParser.getInstance().parse(preparedStatement.executeQuery(), new User());
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return resultList;
    }

    public boolean authUser(String login, String password) {
        boolean result = false;
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy
                     .prepareStatement("select * from users where login = ? and password = ?")) {
            preparedStatement.setString(1, login);
            preparedStatement.setString(2, password);
            result = preparedStatement.executeQuery().next();
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return result;
    }

    public User getByLogin(String login) {
        User user = new User();
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy
                     .prepareStatement("select * from users where login = ?")) {
            preparedStatement.setString(1, login);
            ArrayList<User> users = ResultSetParser.getInstance().parse(preparedStatement.executeQuery(), new User());
            if (!users.isEmpty()) {
                user = users.get(0);
                user.setRole(getRole(user.getRole_id()));
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
        return user;
    }

    private int getRoleId(Role role) {
        int roleId = 0;
        String GET_ROLEID_SQL = "select role_id from roles where role_name = ?";
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement(GET_ROLEID_SQL)) {
            preparedStatement.setString(1, role.name());
            ResultSet resultSet = preparedStatement.executeQuery();
            if (resultSet.next()) {
                roleId = resultSet.getInt(1);
            }
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return roleId;
    }

    private Role getRole(int id) {
        Role role = null;
        String GET_ROLEID_SQL = "select role_name from roles where role_id = ?";
        try (ConnectionProxy connectionProxy = TransactionManager.getInstance().getConnection();
             PreparedStatement preparedStatement = connectionProxy.prepareStatement(GET_ROLEID_SQL)) {
            preparedStatement.setInt(1, id);
            ResultSet resultSet = preparedStatement.executeQuery();
            if (resultSet.next()) {
                role = Role.valueOf(resultSet.getString(1).toUpperCase());
            }
        } catch (SQLException e) {
            LOGGER.error(SQL_EXCEPTION, e);
        }
        return role;
    }
}
